title: UNISON Technologies
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.unisontech.org
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#ef4444"
  systems:
    - name: Website
      description: The main website
      category: Uncategorized
      link: https://unisontech.org
    - name: Assets
      description: Reliant on Cloudflare and Netlify
      category: Uncategorized
    - name: Umami
      category: Uncategorized
      description: Umami is an anonymous, privacy-focused analytics service. No
        personal information or IP addresses is ever logged.
    - name: Short Link Service
      category: Uncategorized
      description: All "go.unisontech.org" links
    - name: Website
      category: Schedules
      link: https://schedules.unisontech.org
    - name: Configuration
      category: Schedules
      description: The actual schedules and other configuration for Schedules
    - name: Stock Digest (website)
      category: Services
      description: Get daily alerts on your tracked stocks
      link: https://stockdigest.unisontech.org
    - name: Stock Digest (backend)
      category: Services
      description: The actual service that powers Stock Digest
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#367BBC"
  enableLastMod: true
  headerTextColor: white
  logo: /img/version-3.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#f59e0b"
  notice: "#367BBC"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#22c55e"
  categories:
    - name: Uncategorized
      untitled: true
    - untitled: false
      name: Schedules
      description: Schedules gives you handy information about your bell schedules,
        such as the current period, the countdown to the next period, and the
        starting time of the next period. For each school, Schedules sends handy
        notifications at predefined intervals and features a full bell schedule
        for each day of the week.
      closed: true
    - name: Services
      closed: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
